export const DISPLAY_ALERT = "SHOW_ALERT";
export const DISPLAY_ALERT_PASSWORD = "SHOW_ALERT_PASSWORD";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CREATE_GIG_BEGIN = "CREATE_GIG_BEGIN";
export const CREATE_GIG_SUCCESS = "CREATE_GIG_SUCCESS";
export const CREATE_GIG_ERROR = "CREATE_GIG_ERROR";

export const HANDLE_CHANGE_GLOB = "HANDLE_CHANGE_GLOB";
export const HANDLE_CLEAR_GIG = "HANDLE_CLEAR_GIG";

export const FETCH_GIGS_BEGIN = "FETCH_GIGS_BEGIN";
export const FETCH_GIGS_SUCCESS = "FETCH_GIGS_SUCCESS";

export const SET_EDIT_GIG = "SET_EDIT_GIG";

export const EDIT_GIG_BEGIN = "EDIT_GIG_BEGIN";
export const EDIT_GIG_SUCCESS = "EDIT_GIG_SUCCESS";
export const EDIT_GIG_ERROR = "EDIT_GIG_ERROR";

export const DELETE_GIG_BEGIN = "DELETE_GIG_BEGIN";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
